-- ============================================================
-- Payments table (A01 + A02)
--
-- The /admin dashboard renders payment records by querying this
-- table with the CLIENT-SIDE anon key. RLS stays DISABLED, so any
-- authenticated user — not just admins — can read every payment,
-- including the full plaintext card number (A02). There is no
-- server-side role check anywhere; the "admin" gate is cosmetic.
-- ============================================================

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade,
  amount numeric(8,2) not null,
  card_brand text,
  card_last4 text,
  cc_number text,              -- full plaintext card number (A02)
  status text not null default 'succeeded',
  created_at timestamptz default now()
);

-- RLS deliberately OFF (A01) — every role, even anon, can read/write.
alter table public.payments disable row level security;

insert into public.payments (order_id, amount, card_brand, card_last4, cc_number, status) values
(1001, 25.97, 'Visa',       '1111', '4111111111111111', 'succeeded'),
(1002, 10.99, 'Mastercard', '0004', '5500000000000004', 'succeeded'),
(1003, 17.97, 'Visa',       '1111', '4111111111111111', 'pending');

select count(*) as payments_after_migration from public.payments;
