-- ============================================================
-- Orders → sequential integer IDs (A01 IDOR)
--
-- Intentionally vulnerable: orders now use small, guessable,
-- sequential integer IDs (starting at 1001) and ROW LEVEL
-- SECURITY stays DISABLED, so the anon key — or any logged-in
-- customer — can read ANY order by id, including the plaintext
-- card number. There is no ownership check anywhere (A01 + A02).
--
--   SELECT * FROM orders WHERE id = 1001;  -- someone else's order
--   POST /api/webhook {"order_id": 1002, "status": "delivered"}
-- ============================================================

-- Nothing references orders.id, so recreate the table with an
-- integer identity PK. Any previous rows are disposable demo data.
drop table if exists public.orders cascade;

create table public.orders (
  id bigint generated by default as identity (start with 1001) primary key,
  user_id uuid references public.users(id),
  restaurant_name text not null,
  items jsonb not null,
  total numeric(8,2) not null,
  status text not null default 'pending',
  cc_number text,              -- plaintext card numbers (A02)
  delivery_address text,       -- address captured at checkout
  created_at timestamptz default now()
);

-- RLS deliberately OFF (A01) — every role, even anon, can read/write.
alter table public.orders disable row level security;

insert into public.orders (user_id, restaurant_name, items, total, status, cc_number, delivery_address) values
('00000000-0000-4000-8000-000000000002', 'Pizza Palace',
 '[{"name":"Margherita Pizza","price":9.99,"qty":2},{"name":"Garlic Breadsticks","price":5.99,"qty":1}]',
 25.97, 'delivered', '4111111111111111', '221B Baker Street, Apt 4, Mumbai 400001'),
('00000000-0000-4000-8000-000000000002', 'Burger Barn',
 '[{"name":"Bacon BBQ Burger","price":10.99,"qty":1}]',
 10.99, 'on_the_way', '5500000000000004', '221B Baker Street, Apt 4, Mumbai 400001'),
('00000000-0000-4000-8000-000000000003', 'Spice Route',
 '[{"name":"Butter Chicken","price":11.99,"qty":1},{"name":"Garlic Naan","price":2.99,"qty":2}]',
 17.97, 'pending', '4111111111111111', 'C-42, Green Park, Delhi 110016');

-- Sanity check (expect 3)
select count(*) as orders_after_migration from public.orders;
